name: Deploy static site to Pages

on:
  push:
    branches: ["main"]   # rulează la push pe branch-ul "main"

permissions:
  contents: read
  pages: write
  id-token: write   # 🔑 necesar pentru autentificare OIDC

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload repository as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # 🔹 tot repo-ul este publicat

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
